### PR TITLE
Allow configuration of the LDAP plugin without installing the LDAP-Plugin

### PR DESCRIPTION
**Pull request by rauchrob**
Currently, it is not possible to configure the LDAP settings in the `sonar.properties` without actually installing the LDAP plugin. Whereas this seems totally reasonable, it turns out to be a problem as soon as the installation of the LDAP plugin fails when using the `sonarqube::plugin` type. This occured to us, when we were trying to setup LDAP behind our corporate proxy.

Therefore, is suggest that it should be possible to specify LDAP configuration using the `sonarqube/ldap` parameter, but without letting this module try to actually install the LDAP plugin. With my suggested change this is possible by declaring sonarqube like

```puppet
class { 'sonarqube':
  ...
  ldap => {
    manage_plugin => false,
    url           => ...,
    ...
  },
}   
```

It does this is backward-compatible way, i.e. if the `manage_plugin` stanza is omitted, it behaves as if it was set to `true`.

### CODE REVIEW

**Comment by racodond** [comment]
I'm not keen to add this feature as it is a very specific use case.
To better understand your issue, could you please detail how you provision the SonarQube plugins (LDAP and the others) then?

**Comment by rauchrob** [comment]
The use case is "Setup Sonarqube with LDAP behind a corporate Proxy", which should be supported, I think. But as I explained above, imho it is currently *impossible* to do this, using this module.

To answer your question: If I remember correctly, these Sonarqube Plugins come as `*.jar` files or something like that, and we just had to drpo them into the corresponding directory within the SonarQube installation directory, eventually restarting the SonarQube service afterwards.

**Comment by racodond** [comment]
This is a use case that should be dealt with by adding a layer on top on this puppet-sonarqube module on your side. It shouldn't be the responsibility of this puppet-sonarqube module to deal with your use case. Moreover, you shouldn't manually drop these jar files after having provisioned your machine.

We're exactly in the same situation (behind a corporate proxy). Here's how we call the sonarqube class, telling the puppet-sonarqube module to get the plugin jar files from a specific group in Nexus:

```
class { 'maven::maven':
    repo => {
      url => 'http://nexus.xxx.com/content/groups/xxx-group-sonarqube'
    }
  }
  ->
  class { 'sonarqube':
    version          => $version,
    ...
```

You should be able to do the same, shouldn't you?

**Comment by rauchrob** [comment]
Ah okay, I think I'm starting to get the big picture now... We have done this before for ruby gems and python packages as well, but the problem is that we have almost no java background. So maven is for java like pip is for python,  and Nexus is like a python package index? Then we definitely should go for a private Nexus instance...

**Comment by racodond** [comment]
Yep, you can install a private repository manager (Nexus or another one).

**Comment by racodond** [comment]
Shall I close this pull request then?

**Comment by rauchrob** [comment]
Yes, please close it. Thanks for your Feedback!
Am 31.07.2015 12:56 nachm. schrieb "David RACODON" <notifications@github.com

**Pull request closed without merging**
