### PR TITLE
Support the sonar.search.javaOpts property

### PR DESCRIPTION
**Pull request by racodond**

### CODE REVIEW

**Comment by carlossg** [comment]
thanks! accepting coffee contributions too :)

**Comment by carlossg** [comment]
and btw, would you like to get write access, handle PRs,...?

**Comment by racodond** [comment]
> thanks! accepting coffee contributions too :)

:-)

> and btw, would you like to get write access, handle PRs,...?

Sure

**Comment by carlossg** [comment]
cool, invitation sent. To push a release just do `rake module:release`, it will tag the code and travis will autodeploy to the forge

**Comment by racodond** [comment]
Could you please remind me how it work to perform a relase?
rake module:release, but how do I set the version?
once done, how long does it take to have the tag created, etc. ?
Thank you

David RACODON
Freelance QA Consultant
LinkedIn <https://ch.linkedin.com/pub/david-racodon/11/62/283> | Twitter
<https://twitter.com/davidracodon>

**Comment by carlossg** [comment]
It uses https://github.com/maestrodev/puppet-blacksmith

It will release the version set in the manifest and bump the patch number. If you want to release a different version just edit the manifest before doing it

The upload to the forge is done by travis from the tag created by `rake module:release` in a short period of time

**Comment by racodond** [comment]
Thanks for the quick answer. It looks like the metadata.json file has been
updated:
https://github.com/maestrodev/puppet-sonarqube/commit/cb20edcd56b1bee2bbf2c10bce9e24bd9e01efed
but I can't see any v2.6.3 tag. Am I missing something?

David RACODON
Freelance QA Consultant
LinkedIn <https://ch.linkedin.com/pub/david-racodon/11/62/283> | Twitter
<https://twitter.com/davidracodon>

**Comment by carlossg** [comment]
v2.6.2 is the version released
2.6.3 is the next version

**Comment by racodond** [comment]
OK. I guess I'm a bit tired... Sorry for the inconvenience.

David RACODON
Freelance QA Consultant
LinkedIn <https://ch.linkedin.com/pub/david-racodon/11/62/283> | Twitter
<https://twitter.com/davidracodon>

**Pull request merged**
