### PR TITLE
Upgrade SonarQube version to Long Term Supported version 4.5.4

### PR DESCRIPTION
**Pull request by racodond**

### CODE REVIEW

**Comment by carlossg** [comment]
LGTM, you should be able to merge it yourself

**Comment by racodond** [comment]
Yep, I can.
I prefer to work with pull requests for you to be able to review my work (if you have time).

**Comment by carlossg** [comment]
PRs are good for the extra tests in all environments but if that passes go for it
Thanks!

**Comment by racodond** [comment]
OK

David RACODON
Freelance QA Consultant
LinkedIn <https://ch.linkedin.com/pub/david-racodon/11/62/283> | Twitter
<https://twitter.com/davidracodon>

**Pull request merged**
