### PR TITLE
Allow to override the LDAP plugin version

### PR DESCRIPTION
**Pull request by pschichtel**

### CODE REVIEW

**Comment by racodond** [comment]
@pschichtel Thanks for your contribution. Could you please set the default version to `1.4` because `1.4.1` does not exist?

**Comment by pschichtel** [comment]
@racodond ops, fixed that. I just upgraded my sonarqube to 5.2 and I also had to override the ldap-plugin groupid:

http://search.maven.org/#search|ga|1|sonar-ldap

**Comment by racodond** [comment]
> ops, fixed that.

Thanks

> I just upgraded my sonarqube to 5.2 and I also had to override the ldap-plugin groupid:

Could you please update the code accordingly? With something like:
```
groupid = $ldap_version < 1.5 ? {
    true => 'org.codehaus.sonar-plugins',
    default => 'org.sonarsource.ldap',
}
```

**Comment by pschichtel** [comment]
Added the selector, but I currently have no system to test the "< 1.5" case

**Comment by racodond** [comment]
> Added the selector

Actually, not that easy :-) (see build log).

Instead, I would remove `sonarqube::plugin { 'sonar-ldap-plugin' : ...` and `sonarqube::plugin { 'sonar-pam-plugin' : ...` and `sonarqube::plugin { 'sonar-crowd-plugin' : ...` and let users manually add the required plugin with the right version, groupid, etc. as all the other plugins. What do you think?

**Comment by pschichtel** [comment]
that's probably the better way. How would configuration be handled? I would personally prefer if the configuration would be bound to the plugin instance (using the concat module).

**Comment by racodond** [comment]
I wouldn't mind if we leave the way LDAP/PAM/Crowd configuration is handled as it is now. But feel free to offer a PR to bound the configuration to the plugin if you want.

**Comment by pschichtel** [comment]
Sorry it took so long, I was kinda busy. I removed the plugins as you suggested, I have not enough free time to go deeper

**Comment by racodond** [comment]
Thanks @pschichtel. For your information, I create another PR to remove those plugins and update the unit tests accordingly: https://github.com/maestrodev/puppet-sonarqube/pull/63

**Pull request closed without merging**
